# Generated by Django 4.2.15 on 2024-08-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_number',
            field=models.PositiveIntegerField(),
        ),
    ]
