# Generated by Django 4.2.15 on 2024-08-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_is_supervisor_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='user_id',
        ),
    ]
