# Generated by Django 4.2.15 on 2024-08-16 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hours', '0001_initial'),
        ('building', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workhoursreport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workhours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extrahours',
            name='floor_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours', to='building.floorsection'),
        ),
        migrations.AddField(
            model_name='extrahours',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workhoursreport',
            unique_together={('user', 'report_date')},
        ),
        migrations.AlterUniqueTogether(
            name='workhours',
            unique_together={('user', 'date')},
        ),
    ]
