# Generated by Django 4.2.15 on 2024-08-16 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingstock',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='building.building'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'product_category')},
        ),
    ]
