# Generated by Django 4.2.15 on 2024-08-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='managers',
            field=models.ManyToManyField(related_name='managed_buildings', to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='building',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_building', to='myapp.employee'),
        ),
        migrations.AddIndex(
            model_name='floorsection',
            index=models.Index(fields=['section_color'], name='building_fl_section_7c5546_idx'),
        ),
    ]
