# Generated by Django 4.2.15 on 2024-08-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_user_id_employee_user'),
        ('building', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='supervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_building', to='myapp.employee'),
        ),
    ]
