# Generated by Django 4.2.15 on 2024-08-24 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_user_id_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0003_alter_building_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='managers',
            field=models.ManyToManyField(limit_choices_to={'is_manager': True}, related_name='managed_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='building',
            name='supervisor',
            field=models.OneToOneField(blank=True, limit_choices_to={'user__is_supervisor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_building', to='myapp.employee'),
        ),
    ]
