# Generated by Django 4.2.15 on 2024-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_alter_floorsection_options_remove_floorsection_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorsection',
            name='section_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
