# Generated by Django 4.2.15 on 2024-08-31 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_phone_number'),
        ('building', '0008_floorsection_assigned_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFloorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_floor_sections', to='myapp.employee')),
            ],
            options={
                'verbose_name': 'Single Floor Section',
            },
        ),
    ]
