# Generated by Django 4.2.15 on 2024-08-31 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_singlefloorsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefloorsection',
            name='floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors_sections', to='building.floor'),
        ),
    ]
