# Generated by Django 4.2.15 on 2024-08-31 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0010_singlefloorsection_floor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefloorsection',
            name='floor_id',
        ),
        migrations.AddField(
            model_name='singlefloorsection',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_floor_sections', to='building.floor'),
        ),
    ]
