# Generated by Django 4.2.15 on 2024-08-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_phone_number'),
        ('building', '0011_remove_singlefloorsection_floor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefloorsection',
            name='assigned_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_floor_sections', to='myapp.employee'),
        ),
    ]
