# Generated by Django 4.2.15 on 2024-08-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_alter_singlefloorsection_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefloorsection',
            name='specific_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
